### ISSUE TITLE
Sortable (Bug/Request)

### ISSUE THREAD

**Issue by CodeWithDennis** [croustibat/filament-jobs-monitor#14]
According to the last update we should have `->sortable()` and default sort `->defaultSort('started_at', 'desc');` but unfortunately this has been applied to the form and not the table. Also im missing the completed_at column on the table.

(Sortable to all columns would be nice)

**Comment by bcollins-oxford** [comment]
Made and proposed the changes -- 
[Pull Request](https://github.com/croustibat/filament-jobs-monitor/pull/15/commits/89c3cca214a6f69f928a21ce92feabd9ea1cd6e9)
