### ISSUE TITLE
Unable to prune

### ISSUE THREAD

**Issue by bcollins-oxford** [croustibat/filament-jobs-monitor#23]
```
php artisan model:prune --model=QueueMonitor

   ErrorException 

  Class "Croustibat\FilamentJobsMonitor\QueueMonitorProvider\Facade" not found

  at vendor/laravel/framework/src/Illuminate/Foundation/AliasLoader.php:80
     76▕             return true;
     77▕         }
     78▕ 
     79▕         if (isset($this->aliases[$alias])) {
  ➜  80▕             return class_alias($this->aliases[$alias], $alias);
     81▕         }
     82▕     }
     83▕ 
     84▕     /**
```

I was able to prune by creating a new QueueMonitorPruning model and extending QueueMonitor.  I'm unsure if I'm missing something but it doesn't seem like it's happy with pruning using a model in the vendor folder.  Could be associated with artisan not finding the model?

**Comment by croustibat** [comment]
that right ! i'm currently investigating

**Comment by croustibat** [comment]
So i manage to reproduce. You should specify the namespace to the model : 

```
$ php artisan model:prune --model="\Croustibat\FilamentJobsMonitor\Models\QueueMonitor"
```

Otherwise, extending the model inside your local app (App/Models) is a good pratice.
