### ISSUE TITLE
package not working well with filament v3 

### ISSUE THREAD

**Issue by bloodykheeng** [croustibat/filament-jobs-monitor#25]
am getting this error Class "App\Filament\Resources\CustomJobMonitorResource" not found 

These are the steps i followed 
composer require croustibat/filament-jobs-monitor
php artisan vendor:publish --tag="filament-jobs-monitor-migrations"
php artisan migrate
php artisan vendor:publish --tag="filament-jobs-monitor-config"
Then i whent to providers/filament/AppPanelProvider.php

and i added there this on the chain ->plugins([
            \Croustibat\FilamentJobsMonitor\FilamentJobsMonitorPlugin::make()
                ->label('Job')
                ->pluralLabel('Jobs')
                ->enableNavigation(true)
                ->navigationIcon('heroicon-o-cpu-chip')
                ->navigationGroup('Settings')
                ->navigationSort(5)
                ->navigationCountBadge(true)
                ->enablePruning(true)
                ->pruningRetention(7)
                ->resource(\App\Filament\Resources\CustomJobMonitorResource::class)
        ])  but after running my program that was working fine its now just crashing please help me guys this is the error am getting Class "App\Filament\Resources\CustomJobMonitorResource" not found  and its referencing to this file providers/filament/AppPanelProvider.php  meaning the way u guys are telling us to register the plugin basing on your documentation has a problem ->plugins([
            \Croustibat\FilamentJobsMonitor\FilamentJobsMonitorPlugin::make()
                ->label('Job')
                ->pluralLabel('Jobs')
                ->enableNavigation(true)
                ->navigationIcon('heroicon-o-cpu-chip')
                ->navigationGroup('Settings')
                ->navigationSort(5)
                ->navigationCountBadge(true)
                ->enablePruning(true)
                ->pruningRetention(7)
                ->resource(\App\Filament\Resources\CustomJobMonitorResource::class)

**Comment by bloodykheeng** [comment]
i had to first comment out the resource 
 ->plugins([
                \Croustibat\FilamentJobsMonitor\FilamentJobsMonitorPlugin::make()
                    ->label('Job')
                    ->pluralLabel('Jobs')
                    ->enableNavigation(true)
                    ->navigationIcon('heroicon-o-cpu-chip')
                    ->navigationGroup('Settings')
                    ->navigationSort(5)
                    ->navigationCountBadge(true)
                    ->enablePruning(true)
                    ->pruningRetention(7)
                // ->resource(\App\Filament\Resources\CustomJobMonitorResource::class)
            ]) am i doing this in the right way or not and please i need guidance

**Comment by valpuia604** [comment]
I think `->resource(\App\Filament\Resources\CustomJobMonitorResource::class)` is for custom resource like if you want to use your own resource instead of default. A clear explanation in docs would needed

**Comment by croustibat** [comment]
yes actually the customJobMonitorResource::class does not exist. it's only if you want/need to add your own resource.
I'll update the readme doc about that !
