### ISSUE TITLE
  Call to a member function getPlugin() on null

### ISSUE THREAD

**Issue by PedroReichert** [croustibat/filament-jobs-monitor#38]
Hello, first of all, thank you for the package.

I'm trying to install it in a fresh Laravel project, and when I add the FilamentJobsMonitorPlugin::make() on AdminPanelProvider, I get the following error:
  Call to a member function getPlugin() on null
![Captura de tela de 2024-03-26 16-54-29](https://github.com/croustibat/filament-jobs-monitor/assets/17646023/9f6dcaff-6078-4118-808d-f11aec4c86fd)

**Comment by tralves** [comment]
I was about to open a PR about the same. I described my findings in [this comment](
https://github.com/croustibat/filament-jobs-monitor/pull/33#issuecomment-2021096923)

**Comment by middaparka** [comment]
+1

**Comment by timlalev** [comment]
+1

**Comment by xyz-09** [comment]
+1

**Comment by storeconn** [comment]
same for me fresh laravel 10 & filament3 or laravel 11 & filament 3

**Comment by Lukaaashek** [comment]
+1

**Comment by croustibat** [comment]
it's working for me on my local setup. but ok I will dig into this problem.

**Comment by glaarg-robert** [comment]
+1

**Comment by timlalev** [comment]
> it's working for me on my local setup. but ok I will dig into this problem.

I faced this issue after updating filament and livewire versions with composer update.

**Comment by croustibat** [comment]
ok i've got something ! 
It's working with Filament 3.1.x but it crashed with Filament 3.2.x
I'm fixing it !

**Comment by croustibat** [comment]
So i came acrosse with this PR to quick fix the getCluster plugin issue. I'm not very happy with the config() inside the resources, but i don't understand why FilamentJobsMonitorPlugin::get()->getCluster() isn't working :/ 

https://github.com/croustibat/filament-jobs-monitor/pull/39

**Comment by timlalev** [comment]
Thanks but still the same: Call to a member function getPlugin() on null

**Comment by glaarg-robert** [comment]
The pull request changes do work.  I added them manually to my local project and it does resolve the issue.  I do not use clusters so I can not say whether it breaks that functionality or not.

**Comment by croustibat** [comment]
Version 2.4.0 is released. It should fix this issue.
