### ISSUE TITLE
I am not able to load jobs

### ISSUE THREAD

**Issue by AnassGBNL** [croustibat/filament-jobs-monitor#6]
Hi,

I have installed the package but i cant see any jobs. Am i doing something wrong?

**Comment by Elephantawareeconomy** [comment]
have you tried running the worker to see if you see any jobs afterwards?

**Comment by AnassGBNL** [comment]
It has been fixed. I am going to change the status to closed. Thanks for your help, guys. For those who are facing the same issue, I resolved it by performing a 'migrate:fresh' followed by an 'optimize:clear' to start with a clean database. Since I had dummy data in my database, it wasn't a problem, but I can imagine it could be an issue if you encounter it on your live server.
